### ISSUE TITLE
Como atualizar o seu fork

### ISSUE THREAD

**Issue by rg3915** [CleitonDeLima/planet-wttd#4]
Alguém ai pode escrever uma wiki sobre como atualizar o seu fork?
Acho que será necessário.

**Comment by paulo-romano** [comment]
Eu posso tentar. Mas acho que o @CleitonDeLima precisa me adicionar como contribuidor.

**Comment by r4bugento** [comment]
É bem fácil atualizar o fork e manter ele sincronizado com o original.
Tem um tutorial bacana do Fernando Daciuk que explica bem:

http://blog.da2k.com.br/2014/01/19/manter-repositorio-github-forkado-sincronizado-com-o-original/

**Comment by rg3915** [comment]
@Paulo vc pode fazer um fork e dar um PR.

EVENTEX  <http://eventex-regis.herokuapp.com/>[image: github]
<https://github.com/rg3915/wttd2>

Regis da Silva
Web Developer
grandeportal.github.io

[image: Aboutme] <https://about.me/rg3915> [image: Linkedin]
<https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile>
 [image: github] <https://github.com/rg3915> [image: matrix]
<http://grandeportal.github.io/>

2016-01-05 10:37 GMT-02:00 R4bugento <notifications@github.com>:

**Comment by CleitonDeLima** [comment]
Hoje a noite eu atualizo o README ou faço a wiki de como fazer o fork. Mais tarde abrir mais Issues.

**Comment by CleitonDeLima** [comment]
Adicionei o Regis e o Paulo como colaboradores, meu tempo ta curto galera, desculpa a demorar para responder.

**Comment by rg3915** [comment]
Ah leleque leque leque leque ... kkkkkkkkkk

**Comment by paulo-romano** [comment]
Ai sim! rsrs

@CleitonDeLima , obrigado. Se quiser eu faço, sem problemas. Já estou fixando o fluxo com ajuda do @rg3915.

Obrigado pela ajuda Regis.

**Comment by paulo-romano** [comment]
@r4bugento esse tutorial ai ta excelente. Valeu.

**Comment by r4bugento** [comment]
é nóis! ;)

**Comment by paulo-romano** [comment]
Bom, já to com o rascunho e criei a pagina. Pode deixar comigo.

**Comment by paulo-romano** [comment]
Pronto, terminei. Vejam como está, por favor.

**Comment by CleitonDeLima** [comment]
Muito bom @paulo-romano !!

**Comment by rg3915** [comment]
@CleitonDeLima jogue o link dele no README.md por favor.

**Comment by CleitonDeLima** [comment]
Ta lá! ;)

**Comment by rg3915** [comment]
Tks
